server:
  port: 8888
spring:
  application:
    name: sprintg-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/riyazpasha/Desktop/Learnings/BackEnd/spring-microservice/git-localconfig-repo/
logging:
  level:
    web: DEBUG