server:
  port: 8000
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-exchange
  jpa:
    show: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      sample-api:
        maxRetryAttempts: 5
        waitDuration: 1s